[versions]
coroutines = "1.6.0"
kotest = "5.2.0"

[libraries]
jetbrains-kotlin-kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test" }
jetbrains-kotlinx-kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotest-kotestAssertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-kotestProperty = { module = "io.kotest:kotest-property", version.ref = "kotest" }
