[versions]
javierscGradlePlugins = "0.1.0-alpha.52"
kotlin = "1.5.30"
kotlinBinaryValidator = "0.7.1"

[libraries]
javiersc-gradlePlugins-allProjects = { module = "com.javiersc.gradle-plugins:all-projects", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-changelog = { module = "com.javiersc.gradle-plugins:changelog", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-codeAnalysis = { module = "com.javiersc.gradle-plugins:code-analysis", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-codeFormatter = { module = "com.javiersc.gradle-plugins:code-formatter", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-docs = { module = "com.javiersc.gradle-plugins:docs", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-kotlinMultiplatform = { module = "com.javiersc.gradle-plugins:kotlin-multiplatform", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-nexus = { module = "com.javiersc.gradle-plugins:nexus", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-pluginAccessors = { module = "com.javiersc.gradle-plugins:plugin-accessors", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-publishKotlinMultiplatform = { module = "com.javiersc.gradle-plugins:publish-kotlin-multiplatform", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-readmeBadges = { module = "com.javiersc.gradle-plugins:readme-badges", version.ref = "javierscGradlePlugins" }
javiersc-gradlePlugins-versioning = { module = "com.javiersc.gradle-plugins:versioning", version.ref = "javierscGradlePlugins" }
jetbrains-kotlin-kotlinGradlePluginX = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
jetbrains-kotlinx-binaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryValidator" }
